### ISSUE TITLE
RAR and ZIP support ?

### ISSUE THREAD

**Issue by GeminiServer** [Celedhrim/docker-kodi-server#2]
Hi, 

seems that this kodi server build doesn't support rar and zip files. Would be cool if you add it.

GeminiServer

**Comment by Celedhrim** [comment]
Hello,

in build log , I have :

```
CPP xbmc/filesystem/ZipDirectory.o
CPP xbmc/filesystem/ZipFile.o
CPP xbmc/filesystem/ZipManager.o
```
So seems zip iif enable

For rar support I see nothing concerning compillation ( build log from official ppa )

have you try this :  "Try settings/appearance/file lists and enable "Suppot browsing into archives"."
seen here => http://openelec.tv/forum/124-raspberry-pi/74124-multi-rar-movies

That's ok for me to add support if it's really missing

**Comment by GeminiServer** [comment]
http://forum.kodi.tv/showthread.php?tid=205402&highlight=archives+debian

Do you also have this in your build log?
```
xbmc/filesystem/RarDirectory.o 
xbmc/filesystem/RarManager.o 
xbmc/filesystem/RarFile.o 
```
https://github.com/xbmc/xbmc/tree/adc196ec0fbe8b191261ab23dc17e8a70b17cad3/xbmc/filesystem

The setting "Suppot browsing into archives" did not exist. I was not able to find this setting in the Source, to set a Value for it. Seems to be raspberry pi Special setting. 

I'm not sure how to define it in the make file, but the #ifdef HAS_FILESYSTEM_RAR must be set some where. 
--> https://github.com/xbmc/xbmc/blob/adc196ec0fbe8b191261ab23dc17e8a70b17cad3/xbmc/filesystem/FileFactory.cpp

**Comment by Celedhrim** [comment]
Do you also have this in your build log? => yes, taken from docker build log

For rar , it seems to be a ./configure option , I'll watch as soon as possible

**Comment by Celedhrim** [comment]
Ok, enable non-free and rar are back

**Comment by GeminiServer** [comment]
:+1: Perfect! 

I cloned and build it. Now it's working. Thank's for the quick fix. 

Best regards, 
GeminiServer
