### ISSUE TITLE
Any plans for arm / raspberry support? 

### ISSUE THREAD

**Issue by Rathna-K** [Celedhrim/docker-kodi-server#20]
Hello I tried building tend dockerfile and running in to several issues as below. Any chance you can add arm to this or is this not possible? If any help needed to compile in Pi I can help. Let me know, thanks

The following packages have unmet dependencies:
 kodi : Depends: kodi-x11 (< 2:18.6+git20200301.0802-final-0bionic.1~) but it is not installable
        Depends: libshairplay0 but it is not installable
        Recommends: i965-va-driver but it is not installable
        Recommends: kodi-peripheral-joystick but it is not installable
        Recommends: kodi-inputstream-adaptive but it is not installable
        Recommends: kodi-inputstream-rtmp but it is not installable
E: Unable to correct problems, you have held broken packages.
The command '/bin/sh -c apt-get update &&     apt-get install -y pulseaudio xpra software-properties-common &&     add-apt-repository -y ppa:team-xbmc/ppa &&     apt-get install -y kodi=2:18.6* &&     apt-get clean &&     rm -rf /var/lib/apt/lists /usr/share/man /usr/share/doc &&     chmod +x /bin/kodi-run-wrapper.sh &&     mkdir /usr/share/kodi/portable_data' returned a non-zero code: 100

**Comment by Celedhrim** [comment]
Hi,

I use team kodi ppa.  I don't know if there is arm ppa from team kodi.

**Comment by Rathna-K** [comment]
I believe they do. If you have the time to make a pi version i can test and provide feedback. 
https://kodi.wiki/view/HOW-TO:Install_Kodi_for_Linux#Raspbian

I tried the Linuxserver.io version but their samba share seems to be broken so I am unable to use theirs unfortunately.

**Comment by luandro** [comment]
+1

Would also love to use on Pi :)

**Comment by Celedhrim** [comment]
Team xbmx/kodi , doest not provide any arm packages.

My docker image is based on their provided binary package. So not posssible for arm.

Maybe using archlinux packages that is fairly up to date would be cool , but no control on version anymore , just build image with the last archlinux package , not very cool :(
