### ISSUE TITLE
kodi 19.0a1 -  tested?

### ISSUE THREAD

**Issue by thezoggy** [Celedhrim/docker-kodi-server#21]
just was curious if you've tested kodi 19.x with this setup

**Comment by Celedhrim** [comment]
Hello,

I use ppa provide by team xbmc : https://launchpad.net/~team-xbmc/+archive/ubuntu/ppa
So if team kodi don't provide package , I cant test.

Anyway , my docker version provide a fake X server and a sound server and then just execute stock kodi.
So it must run flawlessly on kodi 19

**Comment by Celedhrim** [comment]
RC is here and they still don't provide linux build :(

Only stable ( 18.9) and nightly ( last commit build)

**Comment by thezoggy** [comment]
I passed this along to kodi devs

**Comment by thezoggy** [comment]
per kodi devs, only ppa for nightlies and final :(

**Comment by Celedhrim** [comment]
Yep , to update at home I need: 
* libreelec 
* ubuntu package

To be the same so i 'im waiting :)

I don't like the idea of nightlies because it's not a define version in the time. it's juste the last commit in master branch :)

**Comment by thezoggy** [comment]
yay, v19 just hit ppa/binaries just got built

**Comment by Celedhrim** [comment]
Yeah ! 

matrix tag already build , lastest is currently building , should be update soon
