### ISSUE TITLE
Unable to open database: MyVideos119 [2026](SSL connection error: unknown error number)

### ISSUE THREAD

**Issue by paulccs** [Celedhrim/docker-kodi-server#25]
I'm having trouble connecting to MySQL from kodi in the container. In the kodi.log it has a line like the following for every database version:
ERROR : Unable to open database: MyVideos119 [2026](SSL connection error: unknown error number)

After running docker exec /bin/bash in the container, I did apt install mysql-client from within the container and was able to connect successfully using the ip 10.8.0.xxx.

I tried running update-ca-certificates from within the container and that didn't help with kodi.

The .kodi (portable_data) directory was copied from an Ubuntu version 20.04 system and I know this build is 18.04. I didn't think that would be an issue, but is it? Any ideas anyone?

(I've upgraded all my x86_64 18.04 systems to 20.04.) Thanks!

**Comment by nite2** [comment]
I am having the same issue, updated image from leia to matrix (it was working before). All my remote kodi instances (rpi/pc/android) are using the database correctly but the docker image cannot connect. Setting ssl=0 in my.cnf and restarting mysql has no effect on this message.

**Comment by nite2** [comment]
I am sorry, i was using wrong mysql configutration directive. Adding skip_ssl to [mysqld] section DOES fix the issue. Of course also permanently disables SSL...
