### ISSUE TITLE
Somehow it doesnt start

### ISSUE THREAD

**Issue by CubeComming** [Celedhrim/docker-kodi-server#26]
So I set up the docker image.
And docker deploys the image but it doesnt start and docker logs show the following:

W: [pulseaudio] main.c: Running in system mode, but --disallow-exit not set.
W: [pulseaudio] main.c: Running in system mode, but --disallow-module-loading not set.
N: [pulseaudio] main.c: Running in system mode, forcibly disabling SHM mode.
N: [pulseaudio] main.c: Running in system mode, forcibly disabling exit idle time.
E: [pulseaudio] main.c: Daemon startup failed.

At the same time i wonder why it needs pulsaudio. Does it need this even if it is headless?

What am i doing wrong?
Can someone please share an example setup in docker?

**Comment by V3L** [comment]
@CubeComming are you able to confirm how you resolved this issue, as I am getting the same error.

**Comment by CubeComming** [comment]
I sadly didn't manage to get it running, but it also did not work with the older Version from Linuxserver so I guess it has something to do with my server setup.... But i am not sure...
