### ISSUE TITLE
Scan Video Libray

### ISSUE THREAD

**Issue by avogabo** [Celedhrim/docker-kodi-server#30]
I don't know why it doesn't scrape new movies. Can you look at some log to see the failure?

**Comment by thezoggy** [comment]
I've also seen it no longer scraping tv series..  I see it getting the scan command but it instantly comes back with nothing to be found

**Comment by Celedhrim** [comment]
Hello,

No issue for me.

Must be your scraper / kodi config

**Comment by thezoggy** [comment]
Are you using thetvdb for tv scraping?

**Comment by Celedhrim** [comment]
No i don't anymore because some issues ( some informations missing) 
+ the fact that tvdb move a to a paid subscription
and just saw : https://forum.kodi.tv/showthread.php?tid=349385&pid=3057373#pid3057373


I switched to tmdb scraper before summer and never regrets it.
