### ISSUE TITLE
19.4 - dockerhub

### ISSUE THREAD

**Issue by thezoggy** [Celedhrim/docker-kodi-server#32]
just fyi looks like you never pushed out update to dockerhub when you updated to 19.4

**Comment by Celedhrim** [comment]
Hello, 

use : registry.ielf.org/kodi/docker-kodi-server:matrix

It's autobuild ! :)

**Comment by thezoggy** [comment]
ty, btw didnt see this on the readme anywhere

**Comment by thezoggy** [comment]
so just to confirm, i can keep using the ielf registry?

**Comment by Celedhrim** [comment]
You can , but it's selfhosted , docker hub will avec a better uptime I think :)

**Comment by thezoggy** [comment]
ack, yeah i saw way slower performance with ielf registry, i'll switch back to dockerhub.  :)
