### ISSUE TITLE
Kodi v20

### ISSUE THREAD

**Issue by thezoggy** [Celedhrim/docker-kodi-server#33]
Kodi v20 is out, can we get a bump 😉

**Comment by Celedhrim** [comment]
It's not as simple , because currently , kodi fail with the embbeded pulseaudio , I have to test things , but i'm in professional travel currently , I will check as soon a possible

**Comment by albebert** [comment]
why pulseaudio ? 

I use your build for managing centralized kodi database. only. 

i don't see the purpose of pulseaudio, but perhaps i'm missing something :) 

i've made tonihgt a build with kodi 20 based on your work (thanks a lot) i've the pulseaudio error but not a problem for me

**Comment by Celedhrim** [comment]
nexus pushed thx @albebert ! :)
