### ISSUE TITLE
Suggestions for instructions

### ISSUE THREAD

**Issue by helmingstay** [Celedhrim/docker-kodi-server#4]
I want to suggest a few edits to the docs:

The following command is ambiguous - the results depend on the state of the system:
`cp -r ~/.kodi ~/kodi-server-profile`

If ~/kodi-server-profile is an existing directory, then the above command creates a directory .kodi inside it.
Otherwise, the command creates a directory named ~/kodi-server-profile containing the contents of ~/.kodi.  I found by trail and error that the second is the one that's needed.

Also, `docker inspect name` shows that port 8089 is exposed.  This is close to but different from the standard web app port of 8080.  So, the user is required to manually edit the kodi config to match the exposed port, which requires some digging. Suggested edits:

"
1. Prepare a full kodi profile with the GUI version.  If you require web access, make sure to enable this, and set the port to 8089.
2. Make a copy of the ~/.kodi directory:  cp -r ~./kodi  ~/kodi-server-profile
"

**Comment by Celedhrim** [comment]
Hello,

Thx for your feedback
I have update documentation with 16.1 release.

Do you think it's more clear now , or it can be improved ?

**Comment by helmingstay** [comment]
Looks good!
