### ISSUE TITLE
thumbnails always re-cached and not shown over UPnP

### ISSUE THREAD

**Issue by greyslater** [Celedhrim/docker-kodi-server#5]
Hi,
- thumbnails getting cached just fine in the thumbnails folder when browsing movies or music on the kodi-webserver-gui but they are not used and are re-cached when refreshing pages on the webserver - I can delete the folders within the thumbnail folder and/or the Textures13.db, the thumbnails folders fill up again but are always re-cached over and over again.
- maybe it has something to do with the first issue because thumbnails are not showed over UPnP

I'm using a full kodi setup on Ubuntu for the config folder - there everything is just fine (caching and thumbnails over UPnP

Can you reproduce this behaviour on your side?

could it be a reason of the headless patch?

Thank you

**Comment by Celedhrim** [comment]
Hi,

The patch just make kodi launch without graphical interface needed.
I will check deeper, but I don't use Upnp so never check this.

**Comment by greyslater** [comment]
I worked a little bit through the debug log files for a specific movie.
Like i mentioned the thumbnail caching works fine:

`DEBUG: Caching image 'http://image.tmdb.org/t/p/original/inVq3FRqcYIRl2la8iZikYYxFNR.jpg' to 'b/b0defc2e.jpg':`
`DEBUG: cached image 'special://masterprofile/Thumbnails/b/b0defc2e.jpg' size 480x720`

but when it comes to serve the image over UPnP there's the 404 NOT FOUND

`DEBUG: Received request to serve '80F012F2A7E6C849C70390ADFC2DF1F8/inVq3FRqcYIRl2la8iZikYYxFNR.jpg' = 'image://http%3a%2f%2fimage.tmdb.org%2ft%2fp%2foriginal%2f/'`
`WARNING: Platinum [platinum.media.server.file.delegate]: NPT_CHECK failed, result=-20005 (NPT_ERROR_NO_SUCH_ITEM) [(ServeFile(request, context, response, NPT_FilePath::Create(m_FileRoot, file_path)))]`
`INFO: Platinum [platinum.core.http.servertask]: PLT_HttpServerSocketTask::Write`
`HTTP/1.1 404 Not Found`
`Content-Disposition: inline; filename=""`
`Date: Tue, 03 May 2016 11:45:49 GMT`
`Content-Length: 132`
`Content-Type: text/html`
`Server: UPnP/1.0 DLNADOC/1.50 Kodi`

on a non headless-kodi the paths and filenames for thumbnails are identical
also the requestet URL for that image:

`"http://172.27.2.12:1645/%25/80F012F2A7E6C849C70390ADFC2DF1F8/inVq3FRqcYIRl2la8iZikYYxFNR.jpg"`

I don't know where this 80F012F2A7E6C849C70390ADFC2DF1F8 is coming from but on normal kodi once the thumbnails are cached they can be served to a UPnP client also without connection to tmdb.org

that's all I found out until now

**Comment by Celedhrim** [comment]
Hi

http://image.tmdb.org/t/p/original/inVq3FRqcYIRl2la8iZikYYxFNR.jpg => ok 

But if I decode 'image://http%3a%2f%2fimage.tmdb.org%2ft%2fp%2foriginal%2f/'

http://image.tmdb.org/t/p/original// => something is missing , it's 404

But I can't explain why only headless version

**Comment by greyslater** [comment]
and I have even less knowledge about what's going on as I'm only user with debuging knowledge :)

could it be something with missing dependencies that are "switched off" with the headless patch?

I have no idea obviously

**Comment by Celedhrim** [comment]
no more idea here :(

Patch only disable gui dependencies , and I can't figure what dependencis cause your issue.
