### ISSUE TITLE
segmentation fault on startup

### ISSUE THREAD

**Issue by Loki-Afro** [Celedhrim/docker-kodi-server#7]
I do get an segmentation fault on startup
```
root@fedora-anubis /home/zarathustra # docker run --net=host -v /root/kodi-server-profile/opt/kodi-server/share/kodi/portable_data --rm -it celedhrim/kodi-server bash                                                                        
root@fedora-anubis:/# ./opt/kodi-server/lib/kodi/kodi.bin --headless --no-test --nolirc -p
ASegmentation fault (core dumped)
```

linuxserver/kods-headless seems to be affected too
http://lime-technology.com/forum/index.php?topic=42439.0

**Comment by vvuk** [comment]
This small patch should fix this:

https://gist.github.com/vvuk/2c914536e012f8ccffb0eee198ff7ea1

But I haven't tested how functional the result is. I'm just looking for a headless library rescan, and I'm exploring an alternate route.

**Comment by Celedhrim** [comment]
I never been affected by segfault like these.

Happen with all branch ?

**Comment by mnestor** [comment]
@vvuk So far your patch is working very well! Thanks!

**Comment by mnestor** [comment]
@Celedhrim It has to do with new setups, if you never had a headless system going before some version of 16 you wind up with this issue. It appears that above patch fixes it, at least for me.

**Comment by Celedhrim** [comment]
Ho ok !

@vvuk , could you open a PR to include your patch ?
